In [ ]:
# Test cases file

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from urllib import request
module_url = f"https://drive.google.com/uc?export=view&id=18y6hLv2bqAyJsIXwVCty58lF0u7yimVq"
module_url2 = f"https://drive.google.com/uc?export=view&id=1gjxxRtNf3hz9-DE-s9nJ_LBOgBXj2x1-"
module_name = 'commentary.txt'
name2 = 'superheros.csv'
with request.urlopen(module_url) as f, open(module_name,'w') as outf, request.urlopen(module_url2) as f2, open(name2,'w') as outf2:
  a = f.read()
  outf.write(a.decode('utf-8'))
  a2 = f2.read()
  outf2.write(a2.decode('utf-8'))

In [3]:
import c12345678 as test1
# replace c12345678 with your own .py library file name
# make sure this .py file is uploaded to Colab and can be seen in the folder left ;)

In [5]:
# Question 1 - Test case 1
print('Test case 1 output is', test1.all_rounder([1, 7, 5], 'append', [3, 4, 2, 104]))
# Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]

# Question 1 - Test case 2
print('Test case 2 output is', test1.all_rounder('#', 'join', "('Jack', 'Mahmut')"))
#Test case 2 output is Jack#Mahmut

Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]
Test case 2 output is Jack#Mahmut


In [6]:
# Question 2 - Test case 1
a = np.asarray([[1,2],[-9, 4]])
b = np.asarray([[3,4,5,6],[1,1,0,-5]])
print(test1.padded_broadcasting(np.add, a, b, -100))
# [[   4.    6.  -95.  -94.]
# [  -8.    5. -100. -105.]]

# Question 2 - Quality check case
print(test1.padded_broadcasting.__doc__)
#    Definition:
#
#    Input:
#
#    Output:

[[   4.    6.  -95.  -94.]
 [  -8.    5. -100. -105.]]

    Definition: This function calculates numpy brodcasting operation
                when the dimensions of the arrays do not satisfy the rules.

    Input: There are four input arguments:
            func: numpy function to be used
            a, b: arrays to be used in the given function
            pad: number to be padded

    Output: This function returns a single numpy array which is the output of
            the padded broadcasting operation.
    


In [9]:
# Question 3 - Test case 1
print(test1.txtanalyser('commentary.txt', 'RED-CARD!', np.mean, 'find'))
# 59.8
# Question 3 - Test case 2
print(test1.txtanalyser('commentary.txt', 'GOOOOOAAL!', np.log, 'count'))
# 241.0

59.8
241.0


In [11]:
# Question 4 - Test case 1
res = test1.find_alphabetical_order('commentary.txt', check_ties=True)
print(res[0])
# Dimitrios Giannoulis hand-balls.

Dimitrios Giannoulis hand-balls.


In [12]:
# Question 5 - Test case 1
a,b,c,d = test1.pd_query()
print(d['Name'])

0               Abraxas
1                 Amazo
2          Anti-Monitor
3            Anti-Venom
4            Apocalypse
5               Bizarro
6            Black Adam
7              Brainiac
8        Captain Marvel
9       Cyborg Superman
10             Darkseid
11            Destroyer
12             Doomsday
13         Doppelganger
14             Dormammu
15        Fallen One II
16                Faora
17             Galactus
18          General Zod
19                 Goku
20                 Hulk
21             Hyperion
22            Jean Grey
23           Juggernaut
24                Magus
25    Martian Manhunter
26                Match
27                 Nova
28            Onslaught
29              Phoenix
30           Power Girl
31             Red Hulk
32             She-Hulk
33        Silver Surfer
34             Stardust
35             Superboy
36       Superboy-Prime
37            Supergirl
38             Superman
39               Thanos
40                 Thor
41          War 