# Test Assignement

## Q1. Basic Programming

In [91]:
def all_rounder(*args):
    if len(args) != 3:
        return "Invalid number of arguments"

    sequence, method, data = args

    # Enclose the sequence in quotes to ensure it is evaluated as a string
    sequence_obj = eval(f'"{sequence}"')
    data_obj = eval(f"{data}")

    # Check if the method exists for the given sequence type
    if not hasattr(sequence_obj, method):
        return f"Invalid method '{method}' for the given sequence type"

    # Get the method function
    method_func = getattr(sequence_obj, method)

    # Perform the operation
    result = method_func(data_obj)

    # Return the result
    return result

# Example test case
result = all_rounder('#', 'join', "('Jack', 'Mahmut')")
print(result)

Jack#Mahmut


## Q2. NumPy

In [98]:
import numpy as np

def padded_broadcasting(func, a, b, pad=1):

    a_length = a.shape[1]
    b_length = b.shape[1]

    length_dif = abs(a_length - b_length)

    a_width = a.shape[0]
    b_width = b.shape[0]

    width_dif = abs(a_width - b_width)

    if a_width > b_width and a_length > b_length:

        pad_width = ((0, width_dif), (0, length_dif))

        b = np.pad(a, pad_width=pad_width, mode='constant', constant_values=pad)

    elif b_width > a_width and b_length > a_length:

        pad_width = ((0, width_dif), (0, length_dif))

        a = np.pad(a, pad_width=pad_width, mode='constant', constant_values=pad)

    elif a_width > b_width and b_length > a_length:

        a_pad_width = ((0, 0), (0, length_dif))

        a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)

        b_pad_width = ((0, width_dif), (0, 0))

        b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

    elif b_width > a_width and a_length > b_length:

        b_pad_width = ((0, 0), (0, length_dif))

        b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

        a_pad_width = ((0, width_dif), (0, 0))

        a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)
    
    # result = func(a, b)
    
    return a, b

# Example usage:
a = np.asarray([[1,2],[-9, 4]])
b = np.asarray([[3,4,5,6],[1,1,0,-5]])

result = padded_broadcasting(np.add, a, b, -100)
print(result)

(array([[ 1,  2],
       [-9,  4]]), array([[ 3,  4,  5,  6],
       [ 1,  1,  0, -5]]))


In [103]:
a = np.asarray([[1,2],[-9, 4]])
b = np.asarray([[3,4,5,6],[1,1,0,-5]])

pad = -100

a_length = a.shape[1]
b_length = b.shape[1]

length_dif = abs(a_length - b_length)

a_width = a.shape[0]
b_width = b.shape[0]

width_dif = abs(a_width - b_width)

if a_width > b_width and a_length > b_length:

    pad_width = ((0, width_dif), (0, length_dif))

    b = np.pad(a, pad_width=pad_width, mode='constant', constant_values=pad)

elif b_width > a_width and b_length > a_length:

    pad_width = ((0, width_dif), (0, length_dif))

    a = np.pad(a, pad_width=pad_width, mode='constant', constant_values=pad)

elif a_width > b_width and b_length > a_length:

    a_pad_width = ((0, 0), (0, length_dif))

    a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)

    b_pad_width = ((0, width_dif), (0, 0))

    b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

elif b_width > a_width and a_length > b_length:

    b_pad_width = ((0, 0), (0, length_dif))

    b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

    a_pad_width = ((0, width_dif), (0, 0))

    a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)

elif b_width > a_width and a_length == b_length:

    a_pad_width = ((0, width_dif), (0, 0))

    a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)

elif b_width < a_width and a_length == b_length:

    b_pad_width = ((0, width_dif), (0, 0))

    b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

elif b_width == a_width and b_length > a_length:

    a_pad_width = ((0, 0), (0, length_dif))

    a = np.pad(a, pad_width=a_pad_width, mode='constant', constant_values=pad)

elif b_width == a_width and a_length > b_length:

    b_pad_width = ((0, 0), (0, length_dif))

    b = np.pad(a, pad_width=b_pad_width, mode='constant', constant_values=pad)

width_dif

0

In [ ]:
import numpy as np

# Sample multidimensional array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# List to add (1D) with the same size as the existing array
list_to_add = [7, 8, 9]

# Convert the list to a 2D array
new_dimension_array = np.array([list_to_add])




Original array:
[[1 2 3]
 [4 5 6]]

List to add:
[7, 8, 9]

Result array after adding the new list along a new axis:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Example object specifying the number of dimensions and lists
num_dimensions = 2
lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create a new NumPy array
new_array = np.array([np.array(sublist) for sublist in lists])

# # Reshape the array based on the specified number of dimensions
# new_shape = (-1,) + (len(lists[0]),) * (num_dimensions - 1)
# new_array = new_array.reshape(new_shape)

print("New NumPy array:")
print(new_array)

New NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
